# Generated by Django 5.0.6 on 2026-04-17 22:33

import apps.contracts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.contracts.models.contract_upload_path)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=5)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting text'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('evidences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'ordering': ('contract', 'position'),
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('medium_risk_count', models.PositiveIntegerField(default=0)),
                ('low_risk_count', models.PositiveIntegerField(default=0)),
                ('clauses_count', models.PositiveIntegerField(default=0)),
                ('engine_version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='contracts.contract')),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['owner', '-created_at'], name='contracts_c_owner_i_41635b_idx'),
        ),
        migrations.AddIndex(
            model_name='clause',
            index=models.Index(fields=['contract', 'position'], name='contracts_c_contrac_27cfb2_idx'),
        ),
    ]
